### ISSUE TITLE
Переработать форум

### ISSUE THREAD

**Issue by affinvestor** [MartSalted/videovolna#2]
Переработать форум.
Проблемы:
1. Сообщения появляются через пару минут после постинга, а не сразу.
2. Нужно оптимизировать ветки - уберем лишние, заведем необходимые. 
3. В теме нужно сделать страницы, а не как сейчас одна страница без перехода на вторую.
Итог: смотрим можно ли сделать это на данном форуме или пишем форум своими руками по новой.

**Comment by MartSalted** [comment]
> * Сообщения появляются через пару минут после постинга, а не сразу.
> * Нужно оптимизировать ветки - уберем лишние, заведем необходимые.
> * В теме нужно сделать страницы, а не как сейчас одна страница без перехода на вторую.
>   Итог: смотрим можно ли сделать это на данном форуме или пишем форум своими руками по новой.

1. В настройках форума стояла задержка публикации, поставил 1 секунду. Поставил ограничение на обьем каринок до 2мб.
2. Напиши мне что и куда надо передвинуть.
3. Подправил код и настройки. теперь темы показывает по 6 штук на страницу. А вот комментарии периодические не переключаются. Проблему ищу. Скорее всего конфликт с каким то плагином.
