### ISSUE TITLE
Регистрация на сайте

### ISSUE THREAD

**Issue by affinvestor** [MartSalted/videovolna#3]
Нужно сделать регистрацию на сайте с помощью соц сетей. Таких как:
1. ФБ
2. Линкедин
3. Инста
4. Вк - под вопросом.

**Comment by MartSalted** [comment]
> Нужно сделать регистрацию на сайте с помощью соц сетей. Таких как:
> 
> 1. ФБ
> 2. Линкедин
> 3. Инста
> 4. Вк - под вопросом.

Подключил фб/линк/инсту к сайту. Установил плагин соцсетей. Авторизация слетает изза другого плагина который обслуживает форум, Нужно время чтобы их интегрировать либо переделать.
