### ISSUE TITLE
Облегчаем сайт

### ISSUE THREAD

**Issue by affinvestor** [MartSalted/videovolna#4]
Облегчаем сайт. То есть просматриваем все плагины и удаляем лишние\нерабочие и т.д.

**Comment by MartSalted** [comment]
> Облегчаем сайт. То есть просматриваем все плагины и удаляем лишние\нерабочие и т.д.

Убрал лишние плагины авторизации. Обновил плагины которые нужны.
Добавил плагин Social Login и bbPress Toolkit
